# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    # CSRF stateless is usually for APIs. Standard forms use sessions.
    # csrf_protection:
    #     stateless_token_ids:
    #         - submit


