services:
  ### PHP-FPM ###
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rhnewlife_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: mysql://root:root@mariadb:3306/rhnewlife?serverVersion=10.11.2-MariaDB&charset=utf8mb4
      MAILER_DSN: smtp://mailhog:1025
    networks:
      - rhnewlife

  ### Nginx ###
  nginx:
    image: nginx:1.27-alpine
    container_name: rhnewlife_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - rhnewlife

  ### MariaDB ###
  mariadb:
    image: mariadb:10.11
    container_name: rhnewlife_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rhnewlife
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - rhnewlife

  ### PHPMyAdmin ###
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: rhnewlife_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on:
      - mariadb
    networks:
      - rhnewlife

  ### MailHog ###
  mailhog:
    image: mailhog/mailhog
    container_name: rhnewlife_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rhnewlife

networks:
  rhnewlife:
    driver: bridge

volumes:
  db_data:
